# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /news/:year/:month/:day/:title/index.html

include: ["atom.xml"]
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "bin", "vendor", "Gemfile", "Gemfile.lock", "build", "publish-production", "publish-staging"]
markdown: kramdown
highlighter: true

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : AeroGear
domain: aerogear.org
author: AeroGear Project
email: aerogear-dev@lists.jboss.org

production_url : http://aerogear.org


# Less compiler
# gems: ['jekyll-less']

# lessc: /css/styles.less , /css/styles.css
